version: "3.7"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: movies_user
      POSTGRES_PASSWORD: movies_password
      POSTGRES_DB: flix_production
    ports:
      - "5432:5432"

  movies-app:
    build:
      context: .
    environment:
      POSTGRES_USER: movies_user
      POSTGRES_PASSWORD: movies_password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    ports:
      - "3000:3000"
    depends_on:
      - postgres
