default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] || 'movies_user' %>
  password: <%= ENV['POSTGRES_PASSWORD'] || 'movies_password' %>
  host: <%= ENV['POSTGRES_HOST'] || 'db' %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>

development:
  <<: *default
  database: flix_development

test:
  <<: *default
  database: flix_test

production:
  <<: *default
  database: flix_production
